import alternativewordings from '../assets/alternativewordings.PNG';
import campuscrawl from '../assets/campuscrawl.jpg';
import psalter from '../assets/psalter.PNG';
import spanishgame from '../assets/spanishgame.PNG';


export const PROJECTS =
[
    {
        id: 0,
        name: "Calvin's Latin Psalter",
        description: "Read John Calvin's Latin translation of Psalms, and listen along to an audio recording (audio not yet recorded for all chapters.) You can also toggle between the Latin and an English translation as you're listening. Created using React Native.",
        links: [{link: "https://github.com/avolzer/psalter", desc: "code"}],
        image: psalter,
        width: 100
    },
    {
        id: 1,
        name: "Exploring Alternative Wordings",
        description: "This project is a prototype created as part of a generative models research project headed by Professor Kenneth Arnold and published in HAI-GEN 2021: 2nd Workshop on Human-AI Co-Creation with Generative Models. It explores how sentence paraphrases can be generated by using existing machine translation models and text prediction. Alternatives are offered at the sentence level, or the sentence can be altered manually at the word level by hovering and selecting a suggested word from the dropdown. At this point the end of the sentence will be updated to suit the new word. Created using Python, Flask, and Vue.",
        links: [{link: "https://github.com/avolzer/Exploring-Alternative-Wordings", desc: "code"}, {link: "http://ceur-ws.org/Vol-2903/IUI21WS-HAIGEN-1.pdf", desc: "paper"}],
        image: alternativewordings,
        width: 500,
    },
    {
        id: 2,
        name: "Spanish Typing Game",
        description: "This was the first project I ever made, after 1 semester of computer science. Spanish words are falling from the sky! Type the English translation of a word to make it disappear. You get a point for every word you translate, and if 3 reach the bottom of the screen it's game over. Created using Python and tkinter.",
        links: [{link: "https://github.com/avolzer/108-project", desc: "code"}],
        image: spanishgame,
        width: 200
    },
    {
        id: 3,
        name: "Campus Crawl",
        description: "A team project that offers a self-guided tour of Calvin University's campus. This app was built by 5 Calvin students (including me) for CS 262: Software Development. Created using React Native.",
        links: [{link: "https://github.com/calvin-cs262-fall2020-teamb", desc: "code"}],
        image: campuscrawl,
        width: 100
    }
]